name: 'Maven License Info Action'
description: 'This file contains a list of the dependencies and their licenses'
inputs:
  work-dir:
    description: 'work dir ("." = current dir)'
    required: false
    default: '.'
  deep:
    description: 'folder scan deep (-1 == endless)'
    required: false
    default: '-1'
  output-dir:
    description: 'output dir for files [licenses.txt, licenses.md, licenses.csv, licenses.json, licenses.xml] ("." = current dir)'
    required: false
    default: 'target/maven-license-info-action'
  exclude-scopes:
    description: 'A comma separated list of scopes to exclude (e.g. test,provided,system)'
    required: false
    default: ''
  fail-license-regex:
    description: 'Will fail when the regex matches a license key'
    required: false
    default: ''
  fail-dependency-regex:
    description: 'Will fail when the regex matches a dependency'
    required: false
    default: ''
  null-to-empty:
    description: 'converts null to empty string'
    required: false
    default: 'true'
outputs:
  scopes:
    description: 'List of scopes e.g. Compile,Test'
  scopes_all:
    description: 'Static list of all available scopes'
  dependency_list:
    description: 'List of dependencies e.g. org.maven:artifact:1.2.3, org.apache:artifact:4.5.6 '
  dependency_count:
    description: 'Number of third party dependencies'
  dependency_count_compile:
    description: 'Number of third party dependencies for scope [compile]'
  dependency_count_import:
    description: 'Number of third party dependencies for scope [import]'
  dependency_count_provided:
    description: 'Number of third party dependencies for scope [provided]'
  dependency_count_runtime:
    description: 'Number of third party dependencies for scope [runtime]'
  dependency_count_system:
    description: 'Number of third party dependencies for scope [system]'
  dependency_count_test:
    description: 'Number of third party dependencies for scope [test]'
  license_count:
    description: 'Number of licenses provided in third party dependencies'
  license_list:
    description: 'List of used licenses'
  license_limited_list:
    description: 'List of licenses which has limits (manual predefined set e.g. APL, GPL, AGPL, MPL, LGPL, EPL, EUPL, CC-BY-SA, CC-BY-NC, Artistic'
  license_count_compile:
    description: 'Number of licenses provided in third party dependencies for scope [compile]'
  license_count_import:
    description: 'Number of licenses provided in third party dependencies for scope [import]'
  license_count_provided:
    description: 'Number of licenses provided in third party dependencies for scope [provided]'
  license_count_runtime:
    description: 'Number of licenses provided in third party dependencies for scope [runtime]'
  license_count_system:
    description: 'Number of licenses provided in third party dependencies for scope [system]'
  license_count_test:
    description: 'Number of licenses provided in third party dependencies for scope [test]'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: file-text
  color: purple
